# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suboutcome',
            name='level',
        ),
    ]
