# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_suboutcome_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='otis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
